"""
Static list of Nobitex-listed assets and their symbol aliases across
external CEX APIs (Binance / KuCoin use slightly different tickers for
the same coin, e.g. MATIC -> POL, RNDR -> RENDER).
"""
from typing import Dict, List, Set
NOBITEX_ALL_ASSETS: List[str] = [
    "BTCUSDT", "ETHUSDT", "DEXEUSDT", "PROMUSDT", "HOMEUSDT", "AEVOUSDT", "GIGGLEUSDT", "BANKUSDT",
    "SAFEUSDT", "LTCUSDT", "XRPUSDT", "BCHUSDT", "BNBUSDT", "AUSDT", "DOGEUSDT", "XLMUSDT",
    "TRXUSDT", "ADAUSDT", "XMRUSDT", "ETCUSDT", "LINKUSDT", "DAIUSDT", "DOTUSDT", "UNIUSDT",
    "AAVEUSDT", "SOLUSDT", "FILUSDT", "GRTUSDT", "SHIBUSDT", "1INCHUSDT", "ATOMUSDT", "AVAXUSDT",
    "AXSUSDT", "BATUSDT", "MASKUSDT", "NEARUSDT", "SNXUSDT", "YFIUSDT", "MANAUSDT", "SANDUSDT",
    "APEUSDT", "WBTCUSDT", "USDCUSDT", "ALGOUSDT", "GMTUSDT", "CHZUSDT", "QNTUSDT", "FLOWUSDT",
    "HBARUSDT", "EGALAUSDT", "ENJUSDT", "CRVUSDT", "LDOUSDT", "DYDXUSDT", "APTUSDT", "FLRUSDT",
    "COMPUSDT", "LRCUSDT", "SUSHIUSDT", "ENSUSDT", "LPTUSDT", "ONEUSDT", "GLMUSDT", "API3USDT",
    "CVCUSDT", "NMRUSDT", "STORJUSDT", "SLPUSDT", "ZRXUSDT", "EGLDUSDT", "IMXUSDT", "FLOKIUSDT",
    "BLURUSDT", "BABYDOGEUSDT", "CELRUSDT", "TUSDT", "ARBUSDT", "MAGICUSDT", "GMXUSDT", "BANDUSDT",
    "CVXUSDT", "GRAMUSDT", "SSVUSDT", "WLDUSDT", "JSTUSDT", "BICOUSDT", "WOOUSDT", "SKLUSDT",
    "NOTUSDT", "TRBUSDT", "PEPEUSDT", "AGLDUSDT", "RSRUSDT", "ETHFIUSDT", "FETUSDT", "MEMEUSDT",
    "UMAUSDT", "ZROUSDT", "DOGSUSDT", "RENDERUSDT", "POLUSDT", "GUSDT", "ONDOUSDT", "CATIUSDT",
    "HMSTRUSDT", "EIGENUSDT", "PAXGUSDT", "XAUTUSDT", "XTZUSDT", "ENAUSDT", "PENDLEUSDT", "XUSDT",
    "ANKRUSDT", "JASMYUSDT", "SUPERUSDT", "CAKEUSDT", "HOTUSDT", "EDUUSDT", "BANANAUSDT", "WUSDT",
    "MOVEUSDT", "ZILUSDT", "STRKUSDT", "METISUSDT", "TURBOUSDT", "COOKIEUSDT", "CGPTUSDT", "SUSDT",
    "ZECUSDT", "INJUSDT", "ATHUSDT", "NEIROUSDT", "BONKUSDT", "MORPHOUSDT", "CATUSDT", "FORMUSDT",
    "WIFUSDT", "RAYUSDT", "TNSRUSDT", "AIXBTUSDT", "VIRTUALUSDT", "KAITOUSDT", "PENGUUSDT", "JUPUSDT",
    "IOUSDT", "PUMPUSDT", "LAYERUSDT", "PNUTUSDT", "ORCAUSDT", "BOMEUSDT", "PYTHUSDT", "SUIUSDT",
    "SYRUPUSDT", "SAHARAUSDT", "JTOUSDT", "SKYUSDT", "LINEAUSDT", "BIOUSDT", "MEUSDT", "KMNOUSDT",
    "MEWUSDT", "SUNUSDT", "AVNTUSDT", "ASTERUSDT", "OPUSDT", "USDEUSDT", "2ZUSDT", "PROVEUSDT",
    "ZORAUSDT", "TOSHIUSDT", "METUSDT", "WALUSDT", "SEIUSDT", "ZENUSDT", "MMTUSDT", "KITEUSDT",
    "BARDUSDT", "CHEEMSUSDT", "BEAMXUSDT", "MOODENGUSDT", "EULUSDT", "WETUSDT", "DOODUSDT", "ATUSDT",
    "FLUIDUSDT", "REDUSDT", "LAUSDT", "HYPEUSDT", "LITUSDT", "SPKUSDT", "BREVUSDT", "ZKUSDT",
    "DASHUSDT", "HUMAUSDT", "ZAMAUSDT", "SENTUSDT", "CHIPUSDT", "AWEUSDT", "BASEDUSDT", "CFGUSDT",
    "ROBOUSDT", "GRASSUSDT", "ZBTUSDT", "EDGEUSDT", "XVSUSDT", "DUSKUSDT", "OPENUSDT", "COTIUSDT",
    "OPGUSDT", "GENIUSUSDT", "SPCXUSDT", "REUSDT", "SYNUSDT", "NVDAUSDT", "AAPLUSDT", "GOOGLUSDT",
    "AMZNUSDT", "TSLAUSDT", "MSFTUSDT", "CETUSUSDT", "ESPUSDT", "AEROUSDT", "SLXUSDT", "PLUMEUSDT",
    "HOLOUSDT", "TSMUSDT", "SKHYUSDT", "BABAUSDT", "IDUSDT", "XAIUSDT", "PEOPLEUSDT", "FXSUSDT",
    "GOATUSDT", "ACTUSDT", "SFPUSDT", "POWRUSDT", "ACHUSDT", "ILVUSDT", "VINEUSDT", "WAXPUSDT",
    "PHAUSDT", "RPLUSDT", "ANIMEUSDT", "STGUSDT", "BIGTIMEUSDT", "USUALUSDT", "COWUSDT", "TWTUSDT",
    "ZENTUSDT", "AUCTIONUSDT", "BNTUSDT", "YGGUSDT", "KNCUSDT",
]

# main_symbol -> list of alternate tickers used by other exchanges/APIs for the same asset.
SYMBOL_ALIASES: Dict[str, List[str]] = {
    "BABYDOGEUSDT": ["BABYDOGE-USDT", "1000000BABYDOGEUSDT"],
    "POLUSDT": ["MATICUSDT", "POL-USDT", "MATIC-USDT"],
    "FETUSDT": ["ASIUSDT", "FET-USDT", "ASI-USDT"],
    "RENDERUSDT": ["RNDRUSDT", "RENDER-USDT", "RNDR-USDT"],
    "SHIBUSDT": ["1000SHIBUSDT", "SHIB-USDT"],
    "BONKUSDT": ["1000BONKUSDT", "BONK-USDT"],
    "PEPEUSDT": ["1000PEPEUSDT", "PEPE-USDT"],
    "FLOKIUSDT": ["1000FLOKIUSDT", "FLOKI-USDT"],
    "CATUSDT": ["1000CATUSDT", "CAT-USDT"],
    "CHEEMSUSDT": ["1000CHEEMSUSDT", "CHEEMS-USDT"],
}




def build_target_symbol_set() -> Set[str]:
    targets = set(NOBITEX_ALL_ASSETS)
    for aliases in SYMBOL_ALIASES.values():
        for alias in aliases:
            targets.add(alias.replace("-", ""))
    return targets


def resolve_alias(raw_symbol: str) -> str:
    """Map any known alias ticker back to its Nobitex canonical symbol."""
    clean = raw_symbol.replace("-", "")
    for main_symbol, aliases in SYMBOL_ALIASES.items():
        if clean == main_symbol or clean in [a.replace("-", "") for a in aliases]:
            return main_symbol
    return clean


TARGET_SYMBOLS: Set[str] = build_target_symbol_set()
